export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const GET_USERS = 'GET_USERS';
export const CREATING_USER = 'CREATING_USER';
export const DELETING_USER = 'DELETING_USER';
export const EDITING_USER = 'EDITING_USER';
export const FETCHING_USER = 'FETCHING_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const LOGIN_IN = 'LOGIN_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const NO_AUTH = 'NO_AUTH';

export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const EDIT_RESTAURANT = 'EDIT_RESTAURANT';
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const CREATING_RESTAURANT = 'CREATING_RESTAURANT';
export const DELETING_RESTAURANT = 'DELETING_RESTAURANT';
export const EDITING_RESTAURANT = 'EDITING_RESTAURANT';
export const FETCHING_RESTAURANT = 'FETCHING_RESTAURANT';
export const CREATE_RESTAURANT_ERROR = 'CREATE_RESTAURANT_ERROR';
export const DELETE_RESTAURANT_ERROR = 'DELETE_RESTAURANT_ERROR';
export const EDIT_RESTAURANT_ERROR = 'EDIT_RESTAURANT_ERROR';
export const GET_RESTAURANTS_ERROR = 'GET_RESTAURANTS_ERROR';

export const CREATE_BLACKLIST = 'CREATE_BLACKLIST';
export const DELETE_BLACKLIST = 'DELETE_BLACKLIST';
export const GET_BLACKLISTS = 'GET_BLACKLISTS';
export const CREATING_BLACKLIST = 'CREATING_BLACKLIST';
export const DELETING_BLACKLIST = 'DELETING_BLACKLIST';
export const FETCHING_BLACKLIST = 'FETCHING_BLACKLIST';
export const CREATE_BLACKLIST_ERROR = 'CREATE_BLACKLIST_ERROR';
export const DELETE_BLACKLIST_ERROR = 'DELETE_BLACKLIST_ERROR';
export const GET_BLACKLIST_ERROR = 'GET_BLACKLIST_ERROR';

export const CREATE_VISITS = 'CREATE_VISITS';
export const DELETE_VISITS = 'DELETE_VISITS';
export const GET_VISITS = 'GET_VISITS';
export const CREATING_VISITS = 'CREATING_VISITS';
export const DELETING_VISITS = 'DELETING_VISITS';
export const FETCHING_VISITS = 'FETCHING_VISITS';
export const CREATE_VISIT_ERROR = 'CREATE_VISIT_ERROR';
export const DELETE_VISIT_ERROR = 'DELETE_VISIT_ERROR';
export const GET_VISIT_ERROR = 'GET_VISIT_ERROR';

export const CREATE_REVIEW = 'CREATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const CREATING_REVIEW = 'CREATING_REVIEW';
export const DELETING_REVIEW = 'DELETING_REVIEW';
export const CREATE_ERROR_REVIEW = 'CREATE_ERROR_REVIEW';
export const DELETE_ERROR_REVIEW = 'DELETE_ERROR_REVIEW';


